apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 50m
              memory: 128Mi
      serviceAccount: watchman